export enum Sources {
    Airplay = "airplay2",
    Bluetooth = "bluetooth",
    DigitalLeft = "digital_left",
    DigitalRight = "digital_right",
    Line = "line", 
    UPnP = "upnp",
    Optical = "optical", 
    OpticalLeft = "optical_left",
    OpticalRight = "optical_right", 
    OpticalJack = "opticaljack", 
    OpticalJackLeft = "opticaljack_left", 
    OpticalJackRight = "opticaljack_right", 
    Phono = "phono", 
    Raat = "raat",
    SpotifyConnect = "spotifyconnect",
}